"use client";

import { SectionWrapper, SectionHeading } from "@/components/portfolio/section-wrapper";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Github } from "lucide-react";

interface Project { title: string; description: string; tech: string[]; github: string }

const projects: Project[] = [
  { title: "Real-Time Fraud Detection Feature Store", description: "Designed and built a real-time feature-store pipeline with Kafka ingestion, Spark Structured Streaming 5-minute tumbling-window aggregates, dual online Redis and offline MinIO/S3 Parquet storage, Docker Compose orchestration, FastAPI scoring, and an XGBoost classifier tracked with MLflow.", tech: ["Kafka", "PySpark", "Redis", "MinIO/S3", "Docker Compose", "FastAPI", "XGBoost", "MLflow"], github: "https://github.com/sameeksham09/fraud-feature-store" },
  { title: "Agentic RAG Document QA System", description: "Built an end-to-end Retrieval-Augmented Generation pipeline with sentence-aware chunking, Hybrid BM25 + Dense retrieval, Reciprocal Rank Fusion, cross-encoder reranking, LLaMA 3.2, Ollama, FastAPI, and Streamlit. Achieved 100% retrieval precision and 0.75 Token F1 on a held-out benchmark.", tech: ["Python", "ChromaDB", "BM25", "SentenceTransformers", "CrossEncoder", "LLaMA 3.2", "Ollama", "FastAPI", "Streamlit"], github: "https://github.com/sameeksham09/GenAI-Document-Reader.git" },
  { title: "LocalBite — Full-Stack Web Application", description: "Architected a full-stack food delivery platform using React, Spring Boot, Docker/Kubernetes, Redis, Stripe, and WebSockets. Designed a real-time operator dashboard and a two-phase dispatch engine for a 1,000+ user market.", tech: ["React", "Spring Boot", "Docker", "Kubernetes", "Redis", "Stripe", "WebSockets"], github: "https://github.com/localbite-davis/localbite.git" },
  { title: "Lily - Voice-First Maternal Health Companion", description: "Built a voice-first maternal health AI grounded in ACOG clinical guidelines, with dual-model validation, deterministic triage rules, and a real-time doctor dashboard with SLA enforcement.", tech: ["Python", "FastAPI", "Claude Sonnet", "Twilio", "ElevenLabs", "Pinecone", "ChromaDB", "PostgreSQL", "React"], github: "https://github.com/localbite-davis/Lily" },
  { title: "Intelligent Traffic Violation Detection System", description: "Developed a real-time video analytics pipeline for helmet, signal, and mobile-phone violations using YOLO and SORT, with Tesseract OCR license plate recognition and a Streamlit interface. Achieved 73% mAP50.", tech: ["Python", "YOLOv8", "OpenCV", "Tesseract OCR", "Streamlit", "MySQL", "SORT"], github: "https://github.com/sameeksham09/Intelligent-Traffic-Violation-Detection-System.git" },
  { title: "Secure Healthcare Portal", description: "Developed a Node.js healthcare file-sharing portal with SHA-256 integrity verification, bcrypt authentication, MongoDB GridFS storage, session management, and automated email alerts across 500+ test transactions.", tech: ["Node.js", "MongoDB", "GridFS", "bcrypt", "SHA-256", "Nodemailer", "Express"], github: "https://github.com/sameeksham09/Secure-Healthcare-Portal.git" },
  { title: "Fake News Detection", description: "Built an NLP and machine learning web application using TF-IDF vectorization, Logistic Regression, and SVM classifiers with confusion-matrix analysis and cross-model accuracy comparison.", tech: ["Python", "Scikit-learn", "TF-IDF", "NLP", "Flask", "HTML/CSS"], github: "https://github.com/sameeksham09/Fake-News-Detection" },
];

export function ProjectsSection() {
  return <SectionWrapper id="projects" label="Projects"><div className="mx-auto max-w-6xl px-6"><SectionHeading>Projects</SectionHeading><div className="grid md:grid-cols-2 gap-6">{projects.map((project) => <article key={project.title} className="group relative flex flex-col rounded-xl border border-border bg-card p-6 transition-all duration-300 hover:border-primary/30 hover:shadow-lg hover:shadow-primary/5"><h3 className="text-lg font-semibold text-foreground mb-2 group-hover:text-primary transition-colors">{project.title}</h3><p className="text-sm text-muted-foreground leading-relaxed mb-4 flex-1">{project.description}</p><div className="flex flex-wrap gap-1.5 mb-5">{project.tech.map((technology) => <Badge key={technology} variant="outline" className="text-xs font-normal font-mono">{technology}</Badge>)}</div><Button variant="outline" size="sm" asChild><a href={project.github} target="_blank" rel="noopener noreferrer"><Github className="size-4" />Code</a></Button></article>)}</div></div></SectionWrapper>;
}
